### ISSUE TITLE
Laggy after update

### ISSUE THREAD

**Issue by Froggo8311** [ONLYOFFICE/DesktopEditors#1220]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0

### Expected Behavior

Onlyoffice has been incredibly laggy after I updated, and it makes it impossible for me to do anything.

### Actual Behavior

N/A

### Additional information

I'm on arch linux, using the `onlyoffice-bin` package from the AUR.

**Comment by maxanier** [comment]
Same for me, I'm running sway and wayland. I tried the Manjaro community package as well as the `onlyoffice-bin` package from AUR and OnlyOffice is so slow that it is not useable.
This is the first time I am installing onlyoffice, so I cannot confirm that it is related to the update

**Comment by mildred** [comment]
I can confirm no problem on Gnome-Shell, but I think I remember having switched to Sway before OnlyOffice became unusable. Also, it does not seem that QT_QPA_PLATFORM=xcb fixes the problem (at least with flatpak)

**Comment by Froggo8311** [comment]
I believe the problem stems from it being run through Xwayland.

**Comment by ceeb9** [comment]
Same issue here. It seems to only redraw after losing and regaining focus.

**Comment by rplanchuelo** [comment]
Same issue (Sway and Arch).

**Comment by rplanchuelo** [comment]
I tried with Appimage, AUR, Flatpak, ... 7.2.1 works ok but I can't work with 7.3

**Comment by clayrisser** [comment]
It's unusably slow for me on Wayland/Sway. I've even tried running it with xwayland with no better performance. This was not a problem in the past.

**Comment by clayrisser** [comment]
Just confirmed on my end that `7.2.1` works fine, but future versions are too slow.

Interesting observation . . .

7.2.1 fails to start with trying to run directly on wayland, but using xwayland it works great. However, future versions start up both without xwayland  or with xwayland with terrible performance. Seems like wayland support was attempted that maybe caused this but. I'm not sure, but hopefully this feedback/observation is helpful.

**Comment by Froggo8311** [comment]
@clayrisser Yikes 😬

**Comment by marrobHD** [comment]
Same issue

**Comment by XDmitryK** [comment]
Hi all. 
You can write a specification your PC hardware? We need statistics on where this problem happened. Version 7.3.3 has been released if this problem repeated, write here please

**Comment by marrobHD** [comment]
The issue still exists on version 7.3.3.
I experience the issue on my notebook (TM1701) & on a Precision Tower 3420 (06C7).

**Comment by ju6ge** [comment]
I am Running:
CPU: AMD Ryzen 9 7950X
RAM: 64GB
GPU: RX 6700XT

**Comment by ceeb9** [comment]
> Hi all. You can write a specification your PC hardware? We need statistics on where this problem happened. Version 7.3.3 has been released if this problem repeated, write here please

Yes, it still happens on version 7.3.3. PC Hardware / Software Info:
    Distro: Arch Linux x86_64
    Kernel: Linux 6.2.8-zen1-1-zen
    WM: Hyprland (running on the Wayland display server. Hyprland is wlroots based)
    CPU: Ryzen 7 3700X
    GPU: RX 6800XT
    RAM: 32GB

**Comment by Froggo8311** [comment]
Yes, it still occurs for me as well.
Distro: Arch Linux x86_64
Model: Acer Aspire 5 (A515-56 v1.26)
Kernel: 6.2.9-x64v3-xanmod1
Compositor: Hyprland
CPU: 11th Gen Intel i5-1135G7 (8 Threads) 2.4GHz
GPU: Intel Tiger Lake LP GT2 (Iris Xe Graphics) (Driver: i915)
RAM: 20GB

**Comment by dluciv** [comment]
Yes, OnlyOffice 7.3 freezes (while CPU heats =)) under any wlroots-based environment. Tested with sway, Hyprland, labwc (I guess it is enough).

Still works smoothly under Plasma (KDE) and Mutter (Gnome) with Wayland.

Works nicely under XOrg.

I can not pretend to say large corporations and majority of users are using sway, but at least if someone finds a workaround, it would be great!

**Comment by dluciv** [comment]
Also posted an [issue for wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3624), feel free to upvote it =)

**Comment by mildred** [comment]
Got bitten by the update again

`sudo flatpak update --commit=6ae98cba3421104f2284ff31ea702d254d1561e6d127d22cf6cb562d21079ce6 org.onlyoffice.desktopeditors`

**Comment by niraami** [comment]
> Got bitten by the update again
> 
> `sudo flatpak update --commit=6ae98cba3421104f2284ff31ea702d254d1561e6d127d22cf6cb562d21079ce6 org.onlyoffice.desktopeditors`

You can also use [`mask`](https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading) to prevent updates.
```
flatpak mask org.onlyoffice.desktopeditors
```

**Comment by dluciv** [comment]
@mildred, @niraami Nice workaround, thank you both!

**Comment by DenisDeeSign** [comment]
There is another issue with the same problem, so this is duplicate of #1208.

**Comment by mtraker** [comment]
Fedora Linux Rawhide.20230530.n.0 (Silverblue Prerelease) x86_64 
4291U1T ThinkPad X220 
WM: sway 
CPU: Intel i5-2520M (4) @ 3.200GHz 
GPU: Intel 2nd Generation Core Processor Family 
Memory: 4611MiB / 7809MiB 

The flatpak version 7.3.3 freeze a lot. But the Appimage 2.7.1 run ok.

**Comment by apapamarkou** [comment]
The problem remains. Tyied Manjaro, Endeavor, Ubuntu Sway editions.

**Comment by clayrisser** [comment]
Any fix for this? Haven't been able to update to a later version for a long time because of this.

**Comment by SHU-red** [comment]
> Fedora Linux Rawhide.20230530.n.0 (Silverblue Prerelease) x86_64 4291U1T ThinkPad X220 WM: sway CPU: Intel i5-2520M (4) @ 3.200GHz GPU: Intel 2nd Generation Core Processor Family Memory: 4611MiB / 7809MiB
> 
> The flatpak version 7.3.3 freeze a lot. But the Appimage 2.7.1 run ok.

Same for me here
Im running Fedora 39 Workstation but installed/using SWAY

- SWAY: Onlyoffice VERY Laggy
- GNOME: Onlyoffice smooth

**Comment by Spennorex** [comment]
Another sway/WLroots arch user here, issue is still present, I'm using Onlyoffice Desktop editors version 7.5.1.23 (deb) as seen from the about page in the app.

Fresh system, AMD Ryzen 9 7900X3D, 32GB DDR5 RAM, AMD RX 7900 XT.
Fans ramp up when opening the application, maxing out a single core at a time jumping around the cores for about a second each, calming older cores as it jumps.

Are there any updates on this issue as of late?

**Comment by dluciv** [comment]
Updated to OnlyOffice 8. Major update, performance improvements were promised. Did not notice any performance improvements for wlroots though =(

**Comment by hugocnobre** [comment]
Similar issue on windows 11. Only Office Desktop very slow and sluggish after an update.

**Comment by Alvinn549** [comment]
Same on me, debian 12 with sway

**Comment by marrobHD** [comment]
> Same on me, debian 12 with sway

Should be fixed already. Which OnlyOffice version are you using?

**Comment by clayrisser** [comment]
I'm still facing this issue on debian 12 with sway

**Comment by Janu-Li** [comment]
Same on Debian 13 with Gnome/Wayland (the same with X.ORG). It becomes laggy for a minute, after the minute it is usable again. This happens 2-5 times a day.
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2378, resource id: 12582975, major code: 130 (Unknown), minor code: 3

**Comment by j3d3** [comment]
This issue is still present on Debian 12 with sway/wlroots. The entire app is unusable due to the incredibly high latency. Tested on flatpak and appimage.

When running the appimage, the message
`QXcbConnection: XCB error: 8 (BadMatch), sequence: 714, resource id: 4194367, major code: 130 (Unknown), minor code: 3`
appears in the console, same as above.
