### ISSUE TITLE
[Feature] Data Validation and Lookup

### ISSUE THREAD

**Issue by regs01** [ONLYOFFICE/DesktopEditors#159]
**Data validation** with lookup combobox by range of cells and by table name. By table name should work via INDIRECT.

_Do you want to request a feature or report a bug?_
Feature.

_What is the current behavior?_
Doesn't work.

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem._
Not a bug. Demo file.
[reftest.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/2722287/reftest.xlsx)

_What is the expected behavior?_
Should work. Works in both MS Office Excel and WPS Spreadsheet.

_Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?_
5.2.83.480. No.

**Comment by Rita-Bubnova** [comment]
Hello, @regs01.

Please fill issue template correctly:
https://github.com/ONLYOFFICE/DesktopEditors/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by regs01** [comment]
What kind of response? I've edited first post.

**Comment by ShockwaveNN** [comment]
@regs01 oh, sorry, github didn't notify if performed changes to post, we tak a look at your issue

**Comment by Rita-Bubnova** [comment]
Thank you for your enhancement.
I created a new issue 41055 in our private issue tracker.

**Comment by regs01** [comment]
Data validation and lookup by range of cells is working in new 5.5.1 version. INDIRECT doesn't work and I can't find UI to set up data validation.

**Comment by Rita-Bubnova** [comment]
@regs01 You are right there is no UI yet, and data verification by table name via INDIRECT does not work yet. Therefore, this issue is open.

**Comment by mcanepa** [comment]
Hi, is there a target version for data validation via UI? I've recently downloaded v6.0.0 and can see dropdown with range cell from another sheet, but couldn't find a way to create or edit.

**Comment by Rita-Bubnova** [comment]
> Hi, is there a target version for data validation via UI? I've recently downloaded v6.0.0 and can see dropdown with range cell from another sheet, but couldn't find a way to create or edit.

Sorry, this is still not done.
We will post here when there is news on this issue.

**Comment by trofim24** [comment]
We've already implemented support for Data Validation in UI in version 6.2.0.
But Data Validation via INDIRECT hasn't worked yet (C4 and C7). @Rita-Bubnova coud you create a new bug in our issue tracker and attach here number?

**Comment by alinasafonova** [comment]
@trofim24 
I created new bug, number 51219.

**Comment by GlassedSilver** [comment]
> [@trofim24](https://github.com/trofim24) I created new bug, number 51219.

can't find the issue

**Comment by regs01** [comment]
> > [@trofim24](https://github.com/trofim24) I created new bug, number 51219.
> 
> can't find the issue

It's their internal bug tracker ticket associated with this GitHub issue.

And unfortunately its still not implemented. No INDIRECT, no any other way to link table from other sheets.

**Comment by GlassedSilver** [comment]
> > > [@trofim24](https://github.com/trofim24) I created new bug, number 51219.
> > 
> > 
> > can't find the issue
> 
> It's their internal bug tracker ticket associated with this GitHub issue.
> 
> And unfortunately its still not implemented. No INDIRECT, no any other way to link table from other sheets.

I see, almost expected something like that. (in another issue I estimated just that a little later)

I assume the internal tracker is not public by any chance, right?
