### ISSUE TITLE
1.5x interface scaling for small HiDPI displays

### ISSUE THREAD

**Issue by rend3r** [ONLYOFFICE/DesktopEditors#53]
ONLYOFFICE does not honour system dpi (scaling 150% or 144 dpi, using 27'' monitor on 3840 × 2160  in my case) so UI elements look too small.
<img width="1920" alt="only_dpi144" src="https://user-images.githubusercontent.com/12601181/27761602-f7f571b0-5e67-11e7-8e43-eac279e1ecb8.png">

Windows 7 SP1 x64

**Comment by 20161220-rootfest** [comment]
The same on Windows 10 - icons and text are small. It would be nice to have "icon size" option or maybe some high-constrast theme.

**Comment by trinh-no** [comment]
Yes. I can confirm this for both Windows 10 and Ubuntu Gnome. We need an option to scale the UI on the Desktop version.

**Comment by maxkadushkin** [comment]
for scaling equal 144 dpi or less is used 1x elements
to switch app manually to 2x scaling, use --force-scale=2 argument to start application

**Comment by trinhno** [comment]
I (and many others too I think) need a more fine-scaled option.  I "only" have a 13.3" 1080p screen. As it is, the icons are too small, but the 2x option is not viable either (960x540 resolution effectively).

**Comment by rend3r** [comment]
Looks much better with --force-scale=2 but still is not perfect
<img width="1902" alt="oo_scale" src="https://user-images.githubusercontent.com/12601181/28755033-bc7dedd8-755a-11e7-8420-ed7b113ea12d.png">

**Comment by maxkadushkin** [comment]
@trinhno unfortunately, we have no solution for fractional values in scaling yet

**Comment by maxkadushkin** [comment]
@rend3r thanks, it'll be fixed in next release

**Comment by Dremor** [comment]
There is a similar problem on the Surface 3 (Scalling 150%, OnlyOffice 4.4.1).

![image](https://user-images.githubusercontent.com/1915939/30477293-efb74d6c-9a0c-11e7-9db9-92913695a03e.png)

Make OnlyOffice quite unusable.

**Comment by memen45** [comment]
Same here on Surface similar device, Windows 10 fully updated and clean install of onlyoffice. 
Screen: 1920x1080 with 12.2". UI is enorm and little space is left for the document. Also part of the UI falls outside the frame and is therefore unreachable.
![naamloos](https://user-images.githubusercontent.com/27782135/31503087-feb759ca-af6e-11e7-80f4-da0e319279e3.jpg)

Cannot find anything under Advanced settings either

**Comment by filkeith** [comment]
I have another problem. With Titlebar. It is so big on 14" Full HD
![image](https://user-images.githubusercontent.com/1285713/32548548-19fdec66-c497-11e7-971e-fe852ebc2581.png)

**Comment by 5haffl** [comment]
@maxkadushkin May I ask if there is any ETA for the new version?

**Comment by maxkadushkin** [comment]
@5haffl what does ETA mean?

**Comment by maxkadushkin** [comment]
@filkeith do you use some flags to launch the app? do you have that bug in new version?

**Comment by filkeith** [comment]
@maxkadushkin nope. I've tried to run in compatibility mode and with different flags, but nothing help. Also someone from your team (xkorolx) on habr said, that he reproduced this bug and that you'll fix it next version.

Problem only appears on fullHD when display size is less then 15', as I understand. I have dell latitude e5450 with 14' display. If you'll connect external monitor and move window to the monitor, title bar become normal size.

**Comment by maxkadushkin** [comment]
@5haffl next release is planed for end of month, but it won't contain big fixes for that issue

**Comment by maxkadushkin** [comment]
@filkeith what xkorolx said is true, your problem is fixed and will be released soon

**Comment by rend3r** [comment]
As for 4.8.6
<img width="1259" alt="only_o_486" src="https://user-images.githubusercontent.com/12601181/35539080-396e90a4-0561-11e8-8aed-8b77fc56ca5f.png">
See no issue for my setup now.

**Comment by filkeith** [comment]
After last update 4.8.7.392 my problem was solved

**Comment by zjuhasz** [comment]
I'm using Solus Linux and everything scales fine except the cursor which is tiny. I'm using the latest snap.

**Comment by arnowelzel** [comment]
5.1.29.348 x64 not working as installed in Windows 10 with 200% UI scaling @ 3840x2160:

![grafik](https://user-images.githubusercontent.com/6613614/41834868-f25462ee-7855-11e8-856f-141a787959f5.png)

With `--force-scale=2` it's way better, so the question is, why is this not detected automatically? Also see: https://msdn.microsoft.com/de-de/library/windows/desktop/dn280510(v=vs.85).aspx

![grafik](https://user-images.githubusercontent.com/6613614/41834972-316ea4d0-7856-11e8-8ae9-7ca589cc1b8a.png)

**Comment by thedonquixotic** [comment]
Yes, I agree, this sort of thing should be detected automatically. It's kind of a pain to be told that the solution is that I have to run the application with flags. I'm not opening up stuff from the command line yah know?

**Comment by thedonquixotic** [comment]
BTW, I did end up fixing it by going into the .exe and under compatibility and HiDPI settings, setting it to ignore and override the systems attempt to use it in a HiDPI way.

**Comment by pdimens** [comment]
I'm having a similar issue, but it doesn't seem that anyone has had this particular issue on this thread, in that the editor on Arch Linux (Manjaro-Deepin) does not honor the scaling 
![image](https://user-images.githubusercontent.com/19176506/48731160-069f6800-ec02-11e8-94ec-f53677ed91cd.png)

**Comment by graynk** [comment]
> I'm having a similar issue, but it doesn't seem that anyone has had this particular issue on this thread, in that the editor on Arch Linux (Manjaro-Deepin) does not honor the scaling
> ![image](https://user-images.githubusercontent.com/19176506/48731160-069f6800-ec02-11e8-94ec-f53677ed91cd.png)

Same issue here on latest KDE Neon.

**Comment by graynk** [comment]
Yeah, so... It's worse now?

![screenshot_20190110_102945](https://user-images.githubusercontent.com/3626328/50948250-a0c5b300-14c3-11e9-918a-191f248cbd49.png)

**Comment by nikaro** [comment]
I don't know if it is related to HiDPI but here what it looks like on Fedora 29, 1920x1080.
![onlyoffice_fedora29_1920x1080](https://user-images.githubusercontent.com/3918653/50956838-fc407280-14bc-11e9-996d-e32f0a54922b.png)

**Comment by ChriKn** [comment]
Same on windows, sad, that it doesn't sclae right (150% on a 1920x1080 13.3" screen)
Wuld love to ditch office (and microsoft) for good.

**Comment by Githopp192** [comment]
Got the same Issue ... very small icons on Windows 10 / Chrom Browser .. OnlyOffice is running in a Docker .. strange thing is .. that did not have got this behave from the beginning .. !?

**Comment by Githopp192** [comment]
ah .. interesting .. just tried to open the same doc on another browser (now Windows 10 Edge)  .. now it properly showing the content in good size .. so i could be also browser related ?!

**Comment by Githopp192** [comment]
https://www.auslogics.com/en/articles/fix-google-chrome-scaling-on-win-10/

**Comment by memen45** [comment]
This thread is about the desktop editor, so the software you install locally, not the server or browser interface.

**Comment by Githopp192** [comment]
Thx memen45 for clarification

**Comment by 0x264f** [comment]
The bug exists long enough, but there is still no solution. I installed the latest version (5.2.8) on Kubuntu 18.04 and faced with the fact that when using a custom DPI in the system, the onlyoffice interface is displayed incorrectly. The --force-scale flag has only fixed values ​​(1,2, ..., n), which does not allow setting the appropriate scale. If I could set at least a scale of 1.5 or 1.7, this would solve the problem, but for now I cannot use the onlyoffice. This happens not only in KDE, but also in Gnome and Unity 7 with a custom scale. In my opinion this is quite a serious bug that requires attention. I think it’s not at all difficult to give users the ability to manually select a scaling value.

**Comment by hoshi411** [comment]
> I'm having a similar issue, but it doesn't seem that anyone has had this particular issue on this thread, in that the editor on Arch Linux (Manjaro-Deepin) does not honor the scaling
> ![image](https://user-images.githubusercontent.com/19176506/48731160-069f6800-ec02-11e8-94ec-f53677ed91cd.png)

Me too.  Ubuntu 18.04 KDE Neon 4k display Surface Pro 3
![onlyoffice](https://user-images.githubusercontent.com/8462696/61990455-ec186b00-b07b-11e9-811c-3f931784335e.png)

**Comment by Aceler** [comment]
Ubuntu 19.04, OO desktop editors 5.3.95.43 from deb.

All is OK.

**Comment by hoshi411** [comment]
I'm using 5.3.95.43 as well.
So is this a KDE thing?  A couple users have posted they have the issue but didn't mention their OS.  

> Ubuntu 19.04, OO desktop editors 5.3.95.43 from deb.
> 

I assume Aceler is using Gnome.  Is that correct?

This is literally the place to post these kinds of issues and many have already confirmed this bug and nothing?

**Comment by hoshi411** [comment]
Exec=QT_SCALE_FACTOR=1.5 QT_AUTO_SCREEN_SET_FACTOR=1.5 /usr/bin/desktopeditors %F

this is in my desktop file and gives me this result.

![onlyoffice2](https://user-images.githubusercontent.com/8462696/62002574-c3f33f80-b141-11e9-9a3c-88d3630d477a.png)

Vertically it scales properly with this hack but I have other issues with shapes not even drawing etc.

**Comment by rend3r** [comment]
https://github.com/ONLYOFFICE/DesktopEditors/issues/217

**Comment by viktor-w** [comment]
> > I'm having a similar issue, but it doesn't seem that anyone has had this particular issue on this thread, in that the editor on Arch Linux (Manjaro-Deepin) does not honor the scaling
> > ![image](https://user-images.githubusercontent.com/19176506/48731160-069f6800-ec02-11e8-94ec-f53677ed91cd.png)
> 
> Me too. Ubuntu 18.04 KDE Neon 4k display Surface Pro 3
> ![onlyoffice](https://user-images.githubusercontent.com/8462696/61990455-ec186b00-b07b-11e9-811c-3f931784335e.png)

I had it too [Manjaro, KDE], but I find workaround method for me:
~$ Exec=QT_FONT_DPI=163 QT_SCREEN_SCALE_FACTORS=1 QT_SCALE_FACTOR=1  /usr/bin/desktopeditors %F

**Comment by jcklpe** [comment]
Frankly kind of insane that this is still an issue 2 years after was initially reported. Is this project even be actively developed still?

Look, I get it, it's open source, and if something's broken then it's better to fix it than to complain but I just find this really disappointing because I had hoped that a viable alternative to the closed source monopoly microsoft has was finally here.

**Comment by arnowelzel** [comment]
@jcklpe yes the project is still in active development.  The current version 5.3.95.84 was released 2019-08-26: https://www.onlyoffice.com/en/download-desktop.aspx. However it seems "HiDPI" is not easy to handle in Linux. In Windows I don't see these problems any longer but I have a number of other applications which either don't support HiDPI at all or only with 100% or 200% but not any factor in betwen, e.g. KeePassXC.

**Comment by arvind-d** [comment]
> > I'm having a similar issue, but it doesn't seem that anyone has had this particular issue on this thread, in that the editor on Arch Linux (Manjaro-Deepin) does not honor the scaling
> > ![image](https://user-images.githubusercontent.com/19176506/48731160-069f6800-ec02-11e8-94ec-f53677ed91cd.png)
> 
> Me too. Ubuntu 18.04 KDE Neon 4k display Surface Pro 3
> ![onlyoffice](https://user-images.githubusercontent.com/8462696/61990455-ec186b00-b07b-11e9-811c-3f931784335e.png)

Same problem running with scale at 2x (wished it could do 1.5x) on Manjaro KDE:
![Screenshot_20190905_233527](https://user-images.githubusercontent.com/5394380/64375022-0e67b600-d036-11e9-8273-dbcb4240e9a3.png)

**Comment by fikrillah** [comment]
Hope this will be fixed soon, onlyoffice is office software i would like to work with in my 12" 1080 laptop screen...

**Comment by vladimirkosolapov** [comment]
This can be easily fixed if developers return the force-device-scale-factor flag with fractional values. For example, I would be fine with 0.75, but with the current force-scale flag, I can only select integer values.

**Comment by nickian** [comment]
I'm having an issue with this as well. Running Kubuntu 18.04 with Force fonts DPI of 110 on a 4k monitor. What it looks like by default:

![screenshot](https://user-images.githubusercontent.com/590678/66167993-27de2c80-e5f9-11e9-8b98-514b614d51d2.png)

Everything is HUGE compared to the rest of my desktop.

Running `desktopeditors --force-scale=1` appears to help at first, but as soon as I try to resize the window the tabs at the top go back to being huge and wonky:

![screenshot2](https://user-images.githubusercontent.com/590678/66167883-b900d380-e5f8-11e9-8455-26ef3a88aec5.png)

**Comment by dreeck** [comment]
> in current version, for scaling equal 144 dpi or less is used 1x elements
> to switch app manually to 2x scaling, use --force-scale=2 argument to start application

Thank you it solves the problem at home (Windows 10 X64)!

**Comment by FeWa-zu** [comment]
> I had it too [Manjaro, KDE], but I find workaround method for me:
> ~$ Exec=QT_FONT_DPI=163 QT_SCREEN_SCALE_FACTORS=1 QT_SCALE_FACTOR=1 /usr/bin/desktopeditors %F

You are my hero, I've already given up on OnlyOffice with Manjaro, but using this as my .desktop-file (with a different path of course) works absolutely perfect!

**Comment by JeremyG** [comment]
Same issue here on Windows 10 with a HP Spectre 13'' x360 (Touch screen).

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/3398608/70131161-1f9a8000-1682-11ea-848a-f1c9d0df6a1c.PNG">

Not a huge deal but it would be really nice to be able to resize it to fit the global scaling parameters. The current size on my computer makes it a bit hard to read and tiring for the eyes.

**Comment by ShockwaveNN** [comment]
There is messages about several troubles in this issue, but I try to make things clear.
Some issue of this thread should be fixed, but I leave this issue open and make this main issue for troubles with HiDPI displays with low phisical size (I think something like 1080 13 inch displays if I remember right, and some other cases with 4K displays). 
For those resolution we should introduce 1.5x display scaling and it in works, but I cannot give any ETA

**Comment by pablox-cl** [comment]
My configuration is 125% (display settings) in a 14" (1920x1080), with no parameters at the start it looks like this (same as `--force-scale=1`):

![scale1](https://user-images.githubusercontent.com/275754/73849748-33409f00-4809-11ea-8e57-a648dd75843a.png)

with `--force-scale=2`, it's a bit too much 😰 

![scale2](https://user-images.githubusercontent.com/275754/73849877-726ef000-4809-11ea-8b19-edd0a5a57d10.JPG)

Numbers inbetween doesn't work (I tried anyways 😅). Is there a workaround?

**Comment by arnowelzel** [comment]
It seems fractional scaling is not supported yet. Also see https://github.com/ONLYOFFICE/DesktopEditors/issues/53#issuecomment-576294085:
"For those resolution we should introduce 1.5x display scaling and it in works, but I cannot give any ETA"

**Comment by ShockwaveNN** [comment]
@arnowelzel Yeap, only 1x and 2x display scaling currently supported

**Comment by vladimirkosolapov** [comment]
@ShockwaveNN, scaling problem is still present in version 5.5.1 or some fix has appeared?

**Comment by ShockwaveNN** [comment]
@vladimirkosolapov Sorry, still not implemented. We hope it will be ready in future version 5.6, but cannot guarantee it

**Comment by regs01** [comment]
150% is needed not only for small displays. It's also common scaling on 27" 4K screens. This requires usage of SVG icons, so they are well rendered. They are fully supported by the engine already.

**Comment by IPv777** [comment]
Here too I would appreciate a 1.5 parameter

**Comment by mateMathieu** [comment]
+1

**Comment by congard** [comment]
+, on 13'' HiDPI laptop it's now unusable

**Comment by Finist992** [comment]
> +, on 13'' HiDPI laptop it's now unusable

I tried in on my FHD 14' - still not fixed.

**Comment by major-mayer** [comment]
I don't know if this was already mentioned, but you can add the `--force-scale=2 ` parameter to the desktop shortcut of ONLYOFFICE Editors and it will work all the time, no matter if you start it from the start-menu, cmd or because you open a document.
This solution is also much better than the HDPI settings, because if you set it to overwrite by the system, the whole application will get very blurry.

The thing i don't understand is why this is still not detected automatically...?
I'm using 5.5.1.78 and still you have to apply this parameter or else the UI will be extremly small on my UHD display.

**Comment by arnowelzel** [comment]
@major-mayer Some people need 1.5x scaling and not 2x. And this is not supported so far.

**Comment by Hades32** [comment]
Why is this issue on the "desktop editors" repo? I just tried OnlyOffice within NextCloud and it was suuuuper small, too...

**Comment by Finist992** [comment]
> Why is this issue on the "desktop editors" repo? I just tried OnlyOffice within NextCloud and it was suuuuper small, too...

Update still hasn't been submitted. I'm waiting for it)

**Comment by ShockwaveNN** [comment]
> Why is this issue on the "desktop editors" repo? I just tried OnlyOffice within NextCloud and it was suuuuper small, too...

Yeah, you're right, this issue actual for DocumentServer too, almost all DesktopEdition issues actual for DocumentServer and since DocumentServer release first - we should move those issues to DocumentServer repo but I prefer no to move them, since I don't think this will be very helpful, but if you really want - you can create another issue at DocumentServer repo

**Comment by alexmarder** [comment]
In Manajaro, I had to unset `QT_QPA_PLATFORMTHEME`, set `QT_AUTO_SCREEN_SCALE_FACTOR=1`, and use `--force-scale=2`. Now it scales and looks correct. Hope this helps someone else.

**Comment by congard** [comment]
> In Manajaro GNOME, I had to unset `QT_QPA_PLATFORMTHEME`, set `QT_AUTO_SCREEN_SCALE_FACTOR=1`, and use `--force-scale=2`. Now it scales and looks correct. Hope this helps someone else.

`--force-scale=2` too big on 1920x1080 13'' screen, this doesn't real solution

**Comment by alexmarder** [comment]
It looks fine on my 1920x1080 display, but I'll admit my setup might be strange. I scale up my HiDPI display by 200%, then scale out my 1080p display by 2x. If the --force-scale=2 is too large, maybe try using a scale of 1, or not using the --force-scale argument.

**Comment by regs01** [comment]
> In Manajaro GNOME, I had to unset `QT_QPA_PLATFORMTHEME`, set `QT_AUTO_SCREEN_SCALE_FACTOR=1`, and use `--force-scale=2`. Now it scales and looks correct. Hope this helps someone else.

--force-scale=2 is 200% scaling, not 150%.

**Comment by rebelwarrior** [comment]
+1 to 150% scaling.

**Comment by matyhaty** [comment]
Can confirm that --force-scale=1 works well on my 14" laptop which is running at 2160x1440 on windows
This should be a high prioirty as without it, the spreadseheets its pretty unsable

**Comment by MacLake** [comment]
On my 108 cm (42.5") monitor LG 43UD79-B the documents look way too big, probably double size (length) compared to the normal look, unlike all other programs I use. The system is Manjaro Linux with Gnome. With the trick `onlyoffice --force-scale=1` (learned from here) it looks normal.

**Comment by taprobane99** [comment]
+1 for 150% scaling

**Comment by purplecandy** [comment]
+1 for 125 or 150% scaling

**Comment by elandx** [comment]
+1 for 150% scaling.

**Comment by TheOnlyNurse** [comment]
Pretty hard to use OnlyOffice without fractional scaling. I'm going to assume by this thread that this issue won't be addressed any time soon.

**Comment by LEONIDAS-0117** [comment]
Same here for me, OnlyOffice is completely unusable without fractional scaling.

**Comment by Real-Gecko** [comment]
So, issue is 3.5 years old, laptops with 1080p and 1440p displays are everywhere and issue is still not resolved?

**Comment by maxkadushkin** [comment]
@Real-Gecko, unfortunately, is not yet, but in development now

**Comment by szaimen** [comment]
> but in development now

@maxkadushkin great to hear! Is there a PR we can subscribe to?

**Comment by maxkadushkin** [comment]
@szaimen, no. it's developing on cpecific branches in deferent modules

**Comment by regs01** [comment]
This could be time-consuming, but shouldn't be difficult. SVG, needed for icons, is already supported.

**Comment by Real-Gecko** [comment]
> @Real-Gecko, unfortunately, is not yet, but in development now

Thanks for feedback, fingers crossed.

**Comment by maxkadushkin** [comment]
> This could be time-consuming, but shouldn't be difficult. SVG, needed for icons, is already supported.

unfortunatelly, but we have some problems to make svg icons that will be render well in different scaling (100%, 125%, 150%, 175%, 200%)

**Comment by arnowelzel** [comment]
> 
> 
> > This could be time-consuming, but shouldn't be difficult. SVG, needed for icons, is already supported.
> 
> yes, but, unfortunatelly, we have some problems to make svg icons that will be render equally well in different scaling (100%, 125%, 150%, 175%, 200%)

What exactly is the problem? I use SVG icons myself in other projects without any issues at any scaling level. Do you have screenhots to illustrate the issue?

**Comment by maxkadushkin** [comment]
![image](https://user-images.githubusercontent.com/17923696/105389478-f263b500-5c28-11eb-890d-2c0952d71f51.png)
for example, currently some our svg icons look good in 100% and 200%, not good in 150% and bad in 125%

**Comment by maxkadushkin** [comment]
I'm not so experienced in svg to say what's the problem

**Comment by regs01** [comment]
> ![image](https://user-images.githubusercontent.com/17923696/105389478-f263b500-5c28-11eb-890d-2c0952d71f51.png)
> for example, currently some our svg icons look good in 100% and 200%, not good in 150% and bad in 125%

Is it using SVG? Or is it PNG pre generated from SVG?

**Comment by maxkadushkin** [comment]
> Is it using SVG? Or is it PNG pre generated from SVG?
it's svg

**Comment by rebelwarrior** [comment]
They don’t look unusable. And the lack of proper scaling makes the app unusable. If you want to you can hide the option for the not-so-good- looking ones in a command line option so only power users can access it.

**Comment by arnowelzel** [comment]
Looks like the scaling is applied after the rendering the SVGs was done. In this case not only the icons would look "blurred" but also everything else as the whole out would not use real pixels on the screen but it would get rendered at 100% and the result will then get scaled. I think when using CANVAS element to output the GUI instead of native GUI rendering this can't be avoided.

**Comment by laurent-simon** [comment]
My two cents: Icons with a not perfect looking is something far less disturbing than the current wrong scaling.  The primary need is to get the correct display scaling, to get a usable application. The icons' perfection problem is a minor detail. It can be deferred if it's a tricky point.

**Comment by rebelwarrior** [comment]
Apparently the scaling affects the text __and__ the icons from one of the previous comments.

**Comment by arnowelzel** [comment]
> Apparently the scaling affects the text __and__ the icons from one of the previous comments.
> […](#)
> Sent from my mobile
> On Jan 23, 2021, at 11:26 AM, Laurent SIMON ***@***.***> wrote: ﻿ My two cents: Icons with a not perfect looking is something far less disturbing than the current wrong scaling. The primary need is to get the correct display scaling, to get a usable application. The icons' perfection problem is a minor detail. It can be deferred if it's a tricky point. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes - and this can not be solved as OnlyOffice is using JavaScript painting on a browser canvas and not native OS rendering. Also the desktop application works this way. When you create a canvas the pixels will be upscaled depening on the OS scaling.

Example:

You create a canvas with width and height of 100 pixels. If the OS scaling is 100% this means exactly 100x100 device pixels:

```
<canvas width="100" height="100" />
```

However - when the OS scaling is 200% the same canvas will get twice as large since all pixels will scaled by factor 2. Browsers work this way to make sure that the size of bitmap elements (like images or a canvas) stay the same relative to text elements which also get larger. However text elements use native rendering and the pixels of a font will always use device pixels.

But at 200% scaling the canvase it will still have only 100x100 pixels. To mitigate this effect, the canvas can be scaled down again using CSS, so the internal canvass ize can be increased to 200x200 pixels match the device resolution:

```
<canvas width="200" height="200" style="width:100px; height:100px" />
```

The problems start, when you don't have even scaling factors like 125% or 150%. In this case, the canvas needs to be scaled down by a factor of 1.25 which is 0.8 or 1.5 which is 0.6666~. This will result in "blurry" pixels and can not be avoided at all:

```
<canvas width="125" height="125" style="width:100px; height:100px" />
<canvas width="150" height="150" style="width:100px; height:100px" />
```

This applies to every browser based application which uses a canvas to draw elements. The only solution to this would be using pure CSS based rendering and not a canvas to render content. But this would be a completely different approach which requires more or less a complete rewrite of the rendering code.

**Comment by laurent-simon** [comment]
> Apparently the scaling affects the text __and__ the icons from one of the previous comments.

Yes, of course. I just say that the most important is to be able to scale the display. If the icons are not always perfectly rendered at a given scale, it's a negligible problem compared to the inability to scale at a size adapted to the DPI.

**Comment by szaimen** [comment]
Any update here? :)

**Comment by anton-degterev** [comment]
If not for this annoying problem, the OnlyOffice could be recommended as the best free desktop office package at the moment. And now, for some users, it is completely unacceptable despite its excellent functionality. For example, for users of 13-inch Full HD laptops. As a result, the lack of fractional scaling becomes the main stop factor that does not allow you to recommend this software to everyone

**Comment by arnowelzel** [comment]
To get this work properly OnlyOffice would need to change from using a canvas to use SVG for output, so the rendering would then be done native and not as pixel graphics. But this is a major change and would take a lot of effort and time to be done.

**Comment by friday** [comment]
Do you speak for (represent) OnlyOffice @arnowelzel? If not maybe we can wait for someone who does to reply?

**Comment by arnowelzel** [comment]
> 
> 
> Do you speak for (represent) OnlyOffice @arnowelzel? If not maybe we can wait for someone who does to reply?

No, I am also just an end user. But I know how OnlyOffice renders the UI and without changing from canvas to SVG outout they will never be able to support 1.5x scaling properly.

**Comment by friday** [comment]
You may be right. I'm not a Desktop App or C++ developer. However there's a [classic workaround](https://www.html5rocks.com/en/tutorials/canvas/hidpi/) for the issue you mentioned, by factoring in the device pixel ratio (scaling factor) when you're creating the canvas. It looks to me like they're already doing this: https://github.com/ONLYOFFICE/desktop-apps/search?q=dpi_ratio

And you can use ctrl + today already to zoom the content (not the menu, header etc). For me in "Document" (Word equivalent) it zooms to 120%,140% and up while in Spreadsheets (Excel equivalent) it's 125%, 150% and up. For normal text I don't think zooming makes it look any blurrier than 100%. Maybe it doesn't apply to normal font rendering though, but rather the SVG icons like the contributor said? In which case, is it really that bad?

**Comment by Real-Gecko** [comment]
> To get this work properly OnlyOffice would need to change from using a canvas to use SVG for output, so the rendering would then be done native and not as pixel graphics. But this is a major change and would take a lot of effort and time to be done.

There's a lot of apps having icon scaling issue in general, here's example of Double Commander
![image](https://user-images.githubusercontent.com/2231969/109454504-8e7da900-7a7e-11eb-8212-3066e89c77ea.png)
However it's a minor issue we can live with, cause functionality is what matters.

**Comment by arnowelzel** [comment]
I don't talk about just the icons - the whole UI is rendered as a bitmap (yes, also with the desktop version) and then scaled afterwards. This scaling only works properly for 100% and 200% but not any values between - this can result into a "blurry" UI. See my explanation above about how canvas rendering works and why certain scaling factors cause problems.

**Comment by arnowelzel** [comment]
Example:

![grafik](https://user-images.githubusercontent.com/6613614/109477282-24620580-7a78-11eb-8e7b-2dd2df65aa5f.png)

You can see that the whole UI is slightly "blurry" - however the font selection "Arial" and "11" is OK since this is not part of the canvas but a <option> element which is rendered by the browser itself at the native resolution.

**Comment by Real-Gecko** [comment]
> You can see that the whole UI is slightly "blurry" - however the font selection "Arial" and "11" is OK since this is not part of the canvas but a element which is rendered by the browser itself at the native resolution.

Yep, that's bad.

**Comment by maxkadushkin** [comment]
> Any update here? :)

it's planned for 6.3 ver.

**Comment by filipworkxs** [comment]
A bit late but as a workaround for Windows 10 you can override application scaling with system scaling by right clicking the binary and clicking on "Compatibility" tab and then on "Change high DPI settings" button. This forces the application to use system scaling from settings but it looks blurry if is fractional.

**Comment by Githopp192** [comment]
it's never to late .. :-) 

Some time ago i did write a short TroubleShooting Document for my users about the OnlyOffice Scaling issue .. 
i had got this issue with a 4K Screen .. .. here is an extraction of it -->

OnlyOffice
Problem with screen scaling/zoom

With certain screen resolutions (like 4K screens) it sometimes happens that OnlyOffice displays the menu fonts and the menus themselves scaled too small. This is already noticeable when opening the documents:

![ScreenShot136](https://user-images.githubusercontent.com/32612067/113517937-48d36500-9583-11eb-8ff1-5116169cf57b.jpg)

  
The problem can be solved by adjusting the browser used to start Nextcloud via the web as follows:
(in this example "Microsoft Edge")


Open the application folder in Explorer where "Edge" was installed:
![ScreenShot137](https://user-images.githubusercontent.com/32612067/113517961-6acce780-9583-11eb-91bb-486f7d16da2d.jpg)

Right click and select properties:
 
![ScreenShot138](https://user-images.githubusercontent.com/32612067/113517974-7fa97b00-9583-11eb-90fc-d471b283865d.jpg)



 

Click on the "Compatibility" tab and then on "Change high DPI settings":
 
![ScreenShot139](https://user-images.githubusercontent.com/32612067/113517993-9fd93a00-9583-11eb-9059-0d95cc1143e9.jpg)


Change this setting from:
 
![ScreenShot140](https://user-images.githubusercontent.com/32612067/113518003-b8495480-9583-11eb-85c4-8d551b67b173.jpg)


to:

 
![ScreenShot141](https://user-images.githubusercontent.com/32612067/113518009-c9926100-9583-11eb-9ff7-4a7695c942e9.jpg)


Now launching OnlyOffice in the cloud properly scaled

![ScreenShot142](https://user-images.githubusercontent.com/32612067/113518016-da42d700-9583-11eb-84f0-6a2b7d8cb111.jpg)

 

Important:

To apply the settings, log out and log in again (or restart PC).

Note: Under certain circumstances, the font in the EDGE browser may be blurred when the scaling is adjusted. This has then to do with this change. If necessary, this can of course be undone again. If necessary, other browsers can be used / tested that can better handle the 4K screen scaling in a better/more perfect way.

**Comment by regs01** [comment]
This isn't really a solution of any form as it just rasterized upscaling.

**Comment by Githopp192** [comment]
that's right .. but it should be more a workaround .. but to be honest .. i got really troubles read the contents with Edge then - and i did revert this "workaround" later on

**Comment by regs01** [comment]
6.3.1 has 150% interface scaling support (Windows, Linux) in change log, but here on Windows 10 2104 (21H1) it's still 200% with 150% system scaling.

**Comment by ShockwaveNN** [comment]
@regs01 Could you create a new issue related to this problem

**Comment by Real-Gecko** [comment]
Just got an update to version 6.3.1 on my Arch Linux machine, looks fantastic with 150% scaling in FHD 
![image](https://user-images.githubusercontent.com/2231969/124446350-27606000-dda2-11eb-849a-acc7bc590ffe.png)

![image](https://user-images.githubusercontent.com/2231969/124446650-70b0af80-dda2-11eb-8be0-7fa8c6f910fe.png)

Thanks!!!

**Comment by regs01** [comment]
> 
> 
> @regs01 Could you create a new issue related to this problem

#662

**Comment by ShockwaveNN** [comment]
I think I'll close this issue because 

1. It's very old - from 2017 originall
2. We released several updates of DesktopEditors including 125% 150% 175% interface scaling
3. Actually this issue is quite a mess and consists of several not directly related problems about scaling

So I think most issues from this issue is resolved, but all other specific situation it's better to create separate issues

**Comment by rommy2015** [comment]
I work on windows 10, I have a 3k resolution on my laptop.  How can I zoom in on the interface : 

1. Using the key "C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe " --force-scale=4 

2. But only the general interface increases.

 3. When I choose to work with Document, the scaling of the interface does not work. Please help me set this up.

**Comment by ShockwaveNN** [comment]
@rommy2015 As far as I remember - we may not support interface scale greater that 200%

We already got an issue about that
https://github.com/ONLYOFFICE/DocumentServer/issues/1513

**Comment by yllekz** [comment]
This was never fixed and is still happening on my system with a 4K monitor. Please re-address this.

**Comment by regs01** [comment]
You forgot to mention OS and window system and display server in case of Linux. And whatever happen when you select specific scaling in OnlyOffice settings.

**Comment by arnowelzel** [comment]
> This was never properly fixed and is still happening on my system with a 4K monitor. No settings fix the enormous UI scaling. Please re-address this.

At least Windows 10 it works fine - and this also applies to the browser version, which also scales OK at 1.5x:

![image](https://user-images.githubusercontent.com/6613614/168469709-fb77a61e-39ab-418b-a108-c4aa297dd48c.png)

![image](https://user-images.githubusercontent.com/6613614/168469697-6c4a8ed0-c49f-45d1-8976-eab821a8cfa2.png)

**Comment by ShockwaveNN** [comment]
@yllekz I think it's better to create a new issue with detailed description of your environment and problem.
Now we have 200% but for your screen maybe something more needed, like 250% or 300% (and we got separate issue for that )

**Comment by Mr-Newlove** [comment]
Really just heed to add UI scale to the settings menu, please.

**Comment by regs01** [comment]
> Really just heed to add UI scale to the settings menu, please.

It is there and has been there for years.

<img width="1213" height="721" alt="Image" src="https://github.com/user-attachments/assets/323e487c-2104-44dc-9fa9-404aebe5d640" />

**Comment by Mr-Newlove** [comment]
@regs01 Thanks! I had a file open and All i could find was the "Advanced" Settings menu here:

<img width="759" height="1055" alt="Image" src="https://github.com/user-attachments/assets/bb39b8c5-1abc-4dfe-9dfd-b71823f7e0e7" />

Going under the "OnlyOffice" menu in the top left lead me to that.

Sorry for the ping. Thanks for pointing that out. Now my whole UI isnt crazy large anymore!
