### ISSUE TITLE
Using xdg-desktop-portal-kde in KDE plasma environment

### ISSUE THREAD

**Issue by Niwton** [ONLYOFFICE/DesktopEditors#712]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

I would like to request the use of xdg-desktop-portal-kde on operating systems that use KDE plasma as the desktop so that it can use the system theme and not pure qt.
![Screenshot_20210918_204132](https://user-images.githubusercontent.com/24793957/133911338-97a0ecd4-ce91-4f5b-abdd-88f8c5fd41f8.png)

![Screenshot_20210918_204215](https://user-images.githubusercontent.com/24793957/133911339-e4cfeae2-e8ce-4686-bbbd-142121ebc779.png)

**Comment by ShockwaveNN** [comment]
@matveevms please take a look

**Comment by matveevms** [comment]
Hello, @Niwton 
Thanks for your request!
I created offer 52701 in our private tracker with your issue.

**Comment by matveevms** [comment]
Hello, @Niwton 
In the new version 7.3 we have implemented a new kind of system windows.
This fixed here:
https://github.com/ONLYOFFICE/desktop-apps/commit/3113dc9e9e0058a934024fecda5d5221240df016
https://github.com/ONLYOFFICE/desktop-apps/commit/86793a3cd25ad3d6679d08793d36bc24e2e230e5

**Comment by DenisDeeSign** [comment]
Since version is released I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by rago666** [comment]
Sadly it is still not fixed in Kde Plasma as it uses GTK file dialog instead of Kde. Tested on both Fedora rpm & Flatpak. 
![bug](https://user-images.githubusercontent.com/51720144/231028753-79b7519a-1df3-403e-af1f-0b4abd7de1f3.png)

**Comment by Niwton** [comment]
> 

the same happens here

**Comment by spoorun** [comment]
Please Reopen, this is not fixed for KDE users.
DesktopEditors is not using the native file picker still.

**Comment by kaimast** [comment]
It's not using the proper desktop portal on GNOME either. You have to give it full access to your filesystem which is not great from a privacy standpoint.

**Comment by matveevms** [comment]
For now, you can enable the desired dialog using the `--xdg-desktop-portal=default` option when starting the application.

**Comment by DioEgizio** [comment]
> For now, you can enable the desired dialog using the `--xdg-desktop-portal=default` option when starting the application.

is there an env var variant of that so it can be put as an override on flatpak?

**Comment by 0blivi0nis** [comment]
Anyone able to get the KDE portal in Hyprland? I tried all the methods above an still getting the kde one

**Comment by atirutw** [comment]
Is it really fixed if the desktop portal file picker isn't the default and requires manually editing the desktop entry as of 9.3.0.140? Making it the default will improve UX consistency for users a lot IMO.
